config/routes.rb
JOPMTS::Application.routes.draw do
  
  get 'account'         => 'users#show'
  get 'account/edit'    => 'users#edit'

  #resources :profiles
  get    'profile'      => 'profiles#show'
  get    'profile/new'  => 'profiles#new',     :as => "new_profile"
  post   'profile'      => 'profiles#create'
  get    'profile/edit' => 'profiles#edit',    :as => "edit_profile"
  put    'profile'      => 'profiles#update',  :as => "update_profile"
  delete 'profile'      => 'profiles#destroy', :as => "delete_profile"

  match '/auth/:provider/callback' => 'authentications#create'
  devise_for :users, :controllers => { :registrations => 'registrations' }

  devise_scope :user do
    match 'users/register_orcid' => 'registrations#register_orcid'
  end

  resources :manuscripts
  resources :authentications
    
  get "home/index"
  root :to => "home#index"

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  belongs_to :authentication
  has_many :other_names, :dependent => :destroy
  
  validates :given_names,   :presence => true
  validates :family_name,   :presence => true
  validates :vocative_name, :presence => true


end

app/controllers/profiles_controller.rb
# Controller for handling profile management and display

class ProfilesController < ApplicationController

  include OrcidProfileHelper

  
  # Only allow a logged-in users to create & update their profiles
  before_filter :authenticate_user!, :only => [:new,:show, :create, :update,:edit, :destroy]

  # Only allow access to public + protected profile  data via OAuth
  before_filter :oauth_required, :only => [:show_cidprofile_full]

  
  def new
    puts "Creating new profile for user " + current_user.email
    if profile = current_user.profile
      redirect_to profile_path, :notice => 'You already have a profile!' and return     
    end
    
    profile_data = {}
    
    # User may have elected to pull in profile info from an external source. If this is the case
    # we'll have some omniauth info in the session
    if session[:omniauth]
    #if session[:omniauth] && session[:params] && session[:params][:retrieve_external]
      
      orcid = session[:omniauth]['uid']
      
      Rails.logger.debug "Got some OAuth credential info from omniauth: " + session[:omniauth]['credentials'].inspect
      profile_data = retrieve_orcid_bio(orcid, session[:omniauth]['credentials']['token'])
      Rails.logger.debug "Profile data from external system: " + profile_data.inspect
      
      flash[:notice] = "Retrieved external profile data for ORCID #{session[:omniauth]['uid']}, please review"
    end    
    
    @profile = Profile.new(profile_data)
  
  end

  def create
    
    @profile = current_user.build_profile(params[:profile])

    if session[:omniauth]
      # Link up the profile with with the source external authn
      authn = Authentication.find_by_provider_and_uid(session[:omniauth]['provider'], session[:omniauth]['uid'])
      @profile.authentication = authn
      session[:omniauth] = nil # clear the omniauth stuff from the session, just in case
    end

    if @profile.save
      puts 'created new profile for user ' + current_user.email
      redirect_to profile_path, :notice => 'Profile was successfully created.'
    else
      render "new"
    end        
  end

  # Show complete profile only to the user who owns it
  def show
    @profile = current_user.profile

    # ToDo: error message if no profile is found for user

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml  => @profile }
      format.json  { render :json => @profile }
    end    
  end

  def edit
    @profile = current_user.profile
  end


  def update
    @profile = current_user.profile
    puts 'Got profile to update='
    pp @profile
    puts "params="
    pp params

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to(profile_path, :notice => 'Profile was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @profile.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @profile = current_user.profile
    @profile.destroy    
    flash[:notice] = "Successfully destroyed profile."
    redirect_to account_url
  end


  private
  
  # Fix cryptic issue resulting in NoMethodError ("undefined method `current_user='" [..]
  def current_user=(user)
    sign_in(user)
  end
  
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_profile_form.html.erb
<%= form_for @profile, :url => update_profile_path do |f| %>


    <label>First / given name(s)</label>
    <div class="controls">
       <%= f.text_field :given_names, :class => "input-xlarge" %>
    </div>

  <p>
    <%= f.label "Last / Family Name" %><br />
    <%= f.text_field :family_name %>
  </p>

  <p>
    <%= f.label "What should we call you?" %><br />
    <%= f.text_field :vocative_name %>
  </p>

<p>
Other names<br />

<%= text_field_tag "other_name_add", nil, :maxlength => 100, :size=> 50  %> 

<%= link_to_function "Add name", "this.click( function(){alert('foo!'); var n = this.value; alert('adding name' + n); })", :class =>"nav_link" %>

<%= submit_tag "Add name", :class => "btn btn-small"  %>
<br />


<%= select_tag "other_name", options_from_collection_for_select(  @profile.other_names, 'name','name') ,:multiple  => true, :class => 'otherNamesSelect' %> 
</p>

  <%= f.submit nil, :class => "btn btn-small btn-primary" %>

<% if @profile.authentication and action_name = 'edit'  -%>
<p>&nbsp;</p>
  <%#= f.submit "Update profile and send changes to ORCID ", :class =>
  "btn btn-small btn-primary" %>
<% end -%>



<% end %>

app/views/profiles/_retrieve_external_profile_form.html.erb
<% if authentications = current_user.authentications  %>
  <% if !authentications.empty? && !params[:retrieve_external_profiledata] %>

<h4>Would you like to retrieve profile data from one of your external identities?</h4>


  <% for authn in current_user.authentications %>
    <%= form_tag "/auth/" + authn.provider , :method => :get do %>

      <%= authn.provider.camelize %>:<%= authn.profile_uri %>
      <span class="button">
        <%= submit_tag "Retrieve", :name => "retrieve_external", :class => "btn btn-small" %>
      </span>

      <%= hidden_field_tag "scope", "/orcid-bio/read-limited"  %>
    <% end %>

    <br />

  <% end %>



  <% elsif params[:retrieve_external] %>
  <h4>Showing profile data from <%= @external_authn.provider %>:<%= @external_authn.uid %></h4>
  <pre>Note: probably should highlight somehow which fields are externally sourced</pre>
  <% end %>
  
<% end %>

app/views/profiles/create.html.erb
<h1>Profiles#create</h1>
<p>Find me in app/views/profiles/create.html.erb</p>

app/views/profiles/edit.html.erb
<h3>Edit profile</h3>

<%= render "profile_form" %>

app/views/profiles/new.html.erb
<h3>Create profile</h3>


<%= render "retrieve_external_profile_form" %>


<!-- ToDo put this in a collapsible block, show if user selects "enter  by hand above? -->

<%= render "profile_form" %>

app/views/profiles/show.html.erb
<!-- biographical info about this contributor-->

<% profile = current_user.profile %>
<p>
  <%= link_to "Edit profile", edit_profile_path %>
| <%= link_to "Delete profile", profile, :confirm => 'Are you sure you want to delete your profile?', :method => :delete, :class => "remove" %>
</p>

<table class="profileTable">
<tbody>
  <tr>
    <td colspan="2" class="profileName"><strong><%= @profile.family_name %>, <%= @profile.given_names %></strong></td>
  </tr>
<% if @profile.authentication -%>
  <tr>
    <td class="profileFieldLabel">ORCID:</td>
    <td class="profileDataCells"><%= @profile.authentication.uid %></td>
  </tr>
  <tr>
    <td class="profileFieldLabel">URL:</td>
    <td class="profileDataCells">http://orcid.org/<%= @profile.authentication.uid %></td>
  </tr>
<% end -%>
  <tr>
    <td class="profileFieldLabel">Other names:</td>
    <td class="profileDataCells">
<%=  
other_names = @profile.other_names
foo = other_names.map! {|n| n.name }
other_names.join("; ")  %>
    </td>
  </tr>
</table>



<!-- bibliographical info, aka works attributed to this contributor-->

<!--
- link to edit pub/works listing
- list pubs
-->

app/views/profiles/show_public.html.erb
<i>Note: main profile display, shows public attributes only</i>

<!-- biographical info about this contributor-->

<p>
  <b>ORCID:</b>
  <%= @profile.cid %>
</p>

<p>
  <b>URL:</b>
  <%= link_to "http://orcid.org/cid/" + @profile.cid, "http://orcid.org/cid/" + @profile.cid %>
</p>

<p>
  <b>First / Given Name:</b>
  <%= @profile.firstname %>
</p>

<p>
  <b>Last / family name:</b>
  <%= @profile.lastname %>
</p>


<p>
  <b>Middle initials:</b>
  <%= @profile.middleinitials %>
</p>

<p>
<b>Other names:</b>
<%=  
other_names = @profile.other_names
foo = other_names.map! {|n| n.name }
other_names.join("; ")  %>

</p>

<!-- bibliographical info, aka works attributed to this contributor-->