config/routes.rb
JOPMTS::Application.routes.draw do
  
  get 'account'         => 'users#show'
  get 'account/edit'    => 'users#edit'

  #resources :profiles
  get    'profile'      => 'profiles#show'
  get    'profile/new'  => 'profiles#new',     :as => "new_profile"
  post   'profile'      => 'profiles#create'
  get    'profile/edit' => 'profiles#edit',    :as => "edit_profile"
  put    'profile'      => 'profiles#update',  :as => "update_profile"
  delete 'profile'      => 'profiles#destroy', :as => "delete_profile"

  match '/auth/:provider/callback' => 'authentications#create'
  devise_for :users, :controllers => { :registrations => 'registrations' }

  devise_scope :user do
    match 'users/register_orcid' => 'registrations#register_orcid'
  end

  resources :manuscripts
  resources :authentications
    
  get "home/index"
  root :to => "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable, :confirmable and :activatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :roles
  has_many :authentications, :dependent => :destroy
  has_many :manuscripts, :dependent => :destroy
  has_one :profile, :dependent => :destroy
  has_many :tokens, :class_name => "OauthToken", :order => "authorized_at desc", :include => [:client_application]

  def apply_omniauth(omniauth)
    authentications.build(:provider => omniauth['provider'], :uid => omniauth['uid'])  
  end

  def password_required?  
    (authentications.empty? || !password.blank?) && super  
  end  
  
end

app/controllers/users_controller.rb
# -*- coding: utf-8 -*-

class UsersController < ApplicationController


  # Only allow a logged-in users to view & update their accounts
  before_filter :authenticate_user!, :only => [:show, :edit]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user]) # create user record
    if @user.save
      
      @profile = @user.profile.new # just empty profile to begin with
      pp @profile
      puts 'rendering new_profile template'
      render 'new_profile', :notice => "Signed up!" and return      
    else
      render "new"
    end
  end

  def show
    @user = current_user    
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
      
<!-- user account information -->

<h3>User account</h3>

<p><b>E-mail:</b> <%= @user.email %></p>
<p><b>Password</b> ******</p>

<p>
<%= link_to "Edit account", edit_user_registration_path %>
</p>

<hr />
<h3>My profile</h3>

<% if profile = current_user.profile %>

<%= link_to "Edit profile", edit_profile_path %> 
| <%= link_to "Delete profile", delete_profile_path, :confirm => 'Are you sure you want to delete your profile?', :method => :delete, :class => "remove" %>

<br />

<table class="profileTable">
<tbody>
  <tr>
    <td colspan="2" class="profileName"><strong><%= profile.family_name %>, <%= profile.given_names %></strong></td>
  </tr>
<% if profile.authentication -%>
  <tr>
    <td class="profileFieldLabel">ORCID:</td>
    <td class="profileDataCells"><%= profile.authentication.uid %></td>
  </tr>
  <tr>
    <td class="profileFieldLabel">URL:</td>
    <td class="profileDataCells">http://orcid.org/<%= profile.authentication.uid %></td>
  </tr>
<% end -%>
  <tr>
    <td class="profileFieldLabel">Other names:</td>
    <td class="profileDataCells">
<%=  
other_names = profile.other_names
foo = other_names.map! {|n| n.name }
other_names.join("; ")  %>
    </td>
  </tr>
</table>



<% else %>

None | <%= link_to "Create my profile now!", new_profile_path, :class => "btn btn-success" %>

<% end%>

<hr />

<h3>External identities currently connected</h3>

<% if authentications = current_user.authentications %>
  <% if !authentications.empty? %>
    <p><strong>You can sign in to this account using:</strong></p>
    <div class="authentications">
      <% for authentication in authentications %>
        <div class="authentication" style="float: left; margin-right: 10px;">
          <%= image_tag "#{authentication.provider}_64.png", :class => "well", :style =>"padding: 2px;" %>
          <div><%= authentication.uid if authentication.uid %><br />
            <%= link_to "Delete", authentication, :confirm => 'Are you sure you want to remove this authentication option?', :method => :delete, :class => "btn btn-mini btn-danger" %>
          </div>
          <div class="clear"></div>
        </div>
      <% end %>
      <div class="clear"></div>
    </div>
  <% else %>
 None
  <% end %>
<% end %>

<p style="clear: both;">&nbsp;</p>
<hr />

  <p><strong>Connect to new service:</strong></p>
  
<div class="authentication" style="float: left; margin-right: 10px;">
  <a href="/auth/orcid" class="auth_provider">
    <%= image_tag "orcid_64.png", :alt => "ORCID", :class => "well", :style =>"padding: 2px;" %>
    <br />
    ORCID
  </a>
</div>
<div class="authentication" style="float: left; margin-right: 10px;">
  <a href="/auth/twitter" class="auth_provider">
    <%= image_tag "twitter_64.png", :size => "64x64", :alt => "Twitter", :class => "well", :style =>"padding: 2px;" %>
    <br />
    Twitter
  </a>
</div>
<!--
<a href="/auth/open_id?openid_url=https://www.google.com/accounts/o8/id" class="auth_provider">
  <%= image_tag "google_64.png", :size => "64x64", :alt => "Google" %>
  <br />
  Google
</a>
-->
<div class="clear"></div>