config/routes.rb
JOPMTS::Application.routes.draw do
  
  get 'account'         => 'users#show'
  get 'account/edit'    => 'users#edit'

  #resources :profiles
  get    'profile'      => 'profiles#show'
  get    'profile/new'  => 'profiles#new',     :as => "new_profile"
  post   'profile'      => 'profiles#create'
  get    'profile/edit' => 'profiles#edit',    :as => "edit_profile"
  put    'profile'      => 'profiles#update',  :as => "update_profile"
  delete 'profile'      => 'profiles#destroy', :as => "delete_profile"

  match '/auth/:provider/callback' => 'authentications#create'
  devise_for :users, :controllers => { :registrations => 'registrations' }

  devise_scope :user do
    match 'users/register_orcid' => 'registrations#register_orcid'
  end

  resources :manuscripts
  resources :authentications
    
  get "home/index"
  root :to => "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def index    
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
  <h2>Welcome to the JoP Manuscript Tracking System</h2>


 <% if user_signed_in? %>
  <% ext_authn =  current_user.authentications %>

      <p>Hello <%= current_user.email %> What would you like to do?</p>

<%= link_to new_manuscript_path, :class => "btn btn-primary btn-large" do %>
      <h3>Submit a manuscript</h3>
<% end %>
&nbsp;&nbsp;&nbsp;
<%= link_to users_register_orcid_path( :destination =>"submit_manuscript"), :class => "btn btn-primary btn-large" do %>
      <h3>Register my ORCID</h3>
<% end %>
      <p />

 <% else %>
      <p>To do anything of interest on this demo site, you need to sign in</p>
      <p>
  <%= link_to "Sign in / sign up", new_user_session_path, :class =>  "btn btn-primary btn-small"  %> 
      </p>
 <% end %>  