config/routes.rb
JOPMTS::Application.routes.draw do
  
  get 'account'         => 'users#show'
  get 'account/edit'    => 'users#edit'

  #resources :profiles
  get    'profile'      => 'profiles#show'
  get    'profile/new'  => 'profiles#new',     :as => "new_profile"
  post   'profile'      => 'profiles#create'
  get    'profile/edit' => 'profiles#edit',    :as => "edit_profile"
  put    'profile'      => 'profiles#update',  :as => "update_profile"
  delete 'profile'      => 'profiles#destroy', :as => "delete_profile"

  match '/auth/:provider/callback' => 'authentications#create'
  devise_for :users, :controllers => { :registrations => 'registrations' }

  devise_scope :user do
    match 'users/register_orcid' => 'registrations#register_orcid'
  end

  resources :manuscripts
  resources :authentications
    
  get "home/index"
  root :to => "home#index"

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Journal of Psychoceramic Manuscript Tracking System</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body>


<div id="banner" class="container">
  <div  class="row">
    <div class="span2">
    <%= link_to root_path do %>
       <%= image_tag "crackpot.png", :alt => "Crackpot, neh" %>
    <% end %>
    </div>
    <div class="span10">
      <h1>Journal of Psychoceramics</h1>
    </div>
    <div class="span10">
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <ul class="nav">
              <li><%= link_to "Home", root_path %></li>
              <% if user_signed_in? %>
              <li><a href="<%= account_path %>"><i class="icon-user icon-white"></i>Account</a></li>
              <%- if current_user.profile -%>
              <li><%= link_to 'Profile', profile_path -%></li>
              <%- end -%>
              <li><a href="<%= manuscripts_path %>"><i class="icon-book icon-white"></i>My manuscripts</a></li>
              <li><%= link_to  'Sign out', destroy_user_session_path %></li>
              <% else %>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
              <% end %> 
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div  class="container">

  <div  class="row">
    <div class="span2">&nbsp;</div>
    <div class="span8">

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
    </div>
    <div class="span2">&nbsp;</div>
  </div>

  <div  class="row">
    <div class="span2">&nbsp;</div>
    <div class="span8">

      
  <%= content_tag :h1, yield(:title) if show_title? %>
  <%= yield %>

    </div>
    <div class="span2">&nbsp;</div>
  </div>
</div>



</body>
</html>